services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: rds.c******.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: ******
      WORDPRESS_DB_PASSWORD: *****
      WORDPRESS_DB_NAME: ********
    volumes:
      - /wordpress:/var/www/html
    networks:
      - tunel

networks:
  tunel:
    driver: bridge
